resources:
- deploy.yaml
- service.yaml
- github.com/partiallyordered/bases/mysql?ref=01e9909a2bfc040dac27bb770f79a1049d833bda

secretGenerator:
- name: connection-manager-api-api-secret
  literals:
  - dummy=DUMMY
- name: mysql
  behavior: merge
  literals:
  - MYSQL_PASSWORD=mcm
  - MYSQL_ROOT_PASSWORD=mcm

configMapGenerator:
- name: mysql
  behavior: merge
  literals:
  - MYSQL_SERVICE=mysql
  - MYSQL_USER=mcm
  - MYSQL_DATABASE=mcm
