name: ci-build-and-test

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - 'main'

env:
  IMAGE_NAME: ${GITHUB_REPOSITORY#*/}
  # IMAGE_TAG: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: ./server
          tags: ${GITHUB_REPOSITORY#*/}:${GITHUB_SHA::6}
          outputs: type=docker,dest=/tmp/${GITHUB_REPOSITORY#*/}.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${GITHUB_REPOSITORY#*/}
          path: /tmp/${GITHUB_REPOSITORY#*/}.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${GITHUB_REPOSITORY#*/}
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/${GITHUB_REPOSITORY#*/}.tar
          docker image ls -a
