name: Publish image
# Notes:
# - need to enable "improved container support":
#   https://docs.github.com/en/packages/guides/enabling-improved-container-support
# - need to add an access token, probably at organisation level
# - need to remove `environment: build`

# TODO: create a tag/release with the version based on the version in package.json every time a
# merge is made to master?
on:
  # TODO: filter on vX.Y.Z (i.e. semantic-ish versioning)- ideally we'd have proper semantic
  # versioning, but let's see what happens. Or don't filter?
  # Or: only publish the :latest tag when the release name is a proper semantic version tag-
  # perhaps even without any suffixes?
  release:
    types: [published]
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    environment: build
    steps:
      # At the time of writing, we need to manually specify the context, as we can't set a
      # subdirectory of the repo as a build context
      # https://github.com/docker/build-push-action/tree/636b4540ec057719fe868a4435761056c89d2fff#git-context
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          context: ./server
          file: ./server/Dockerfile
          # tags need to have the registry name in them, except for Dockerhub, which is the default
          # See: https://docs.github.com/en/enterprise-server@2.22/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          # And: https://docs.github.com/en/enterprise-server@2.22/actions/reference/context-and-expression-syntax-for-github-actions#functions
          tags: |
            ghcr.io/${{ github.repository }}/connection-manager-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
