name: Publish image
# Notes:
# - need to enable "improved container support":
#   https://docs.github.com/en/packages/guides/enabling-improved-container-support
# - need to add an access token, probably at organisation level
# - need to remove `environment: build`

# TODO: create a tag/release with the version based on the version in package.json every time a
# merge is made to master?
on:
  push:
    branches: master
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

jobs:
  main:
    runs-on: ubuntu-latest
    environment: build
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          file: ./server/Dockerfile
          # tags need to have the registry name in them, except for Dockerhub, which is the default
          tags: ghcr.io/msk-/connection-manager-api/connection-manager-api:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
