# Notes:
# - need to enable "improved container support":
#   https://docs.github.com/en/packages/guides/enabling-improved-container-support
# - need to add an access token to secrets (in this case called CR_PAT), probably good to do this
#   at organisation level. This access token needs to be a personal access token at the time of
#   writing. This works, because the organisation policy gives organisation members permission to
#   publish packages.
# - looks like you'll need to manually make the published image public by visiting:
#   https://github.com/orgs/mojaloop/packages

# TODO: create a tag/release with the version based on the version in package.json every time a
# merge is made to master? Prevent any merges to master without a code change? (That's probably
# tricky- what to do about documentation changes etc.? Perhaps build the container image, see if
# the checksum is the same as the existing one, and prevent pushes to master that change the
# container checksum without changing the package.json version?).

# At the time of writing, it's
#  - not possible to filter here on the name of the release, for example we cannot say "only run
#    this job on releases with a name matching v[0-9]+.[0-9]+.[0-9]+" (i.e. a pseudo semantic
#    version)
#  - possible to trigger the job on a tag matching a pseudo semantic version as described above,
#    but also possible to push multiple tags at once, and difficult to extract the tag name using
#    the information available to the job. As one example: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
#    it isn't possible to use ${{ github.ref }} because that is of the form /refs/tags/$tag_name,
#    and the functionality available here: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions
#    is not sufficient to extract the tag.
#    Similarly, `github.event.push` doesn't seem to provide an easy way to extract the tag that
#    triggered the event, and does appear to potentially contain multiple tags per push:
#    https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
#    https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push

name: Publish image

on:
  release:
    types: [published]

jobs:
  main:
    # You might be tempted to try something like this:
    #   if: ${{ github.event.release.tag_name ~= v[0-9]+\.[0-9]+\.[0-9]+ }}
    # Unfortunately, this is plain unsupported at the time of writing.
    runs-on: ubuntu-latest
    steps:
      -
        # At the time of writing, we need to manually specify the context, as we can't set a
        # subdirectory of the repo as a build context
        # https://github.com/docker/build-push-action/tree/636b4540ec057719fe868a4435761056c89d2fff#git-context
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Set build date-time in environment
        id: date
        run: echo '::set-output name=date::$(date --rfc-3339=seconds)'
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          # The following two lines are required in concert with the checkout action above, because
          # the Dockerfile is in a subdirectory in the repo.
          context: ./server
          file: ./server/Dockerfile
          # Except for Dockerhub, which is the default, tags need to have the registry name in
          # them, e.g. ghcr.io for Github container registry, or gcr.io for Google container
          # registry.
          # Note that the following tags will look like:
          #   ghcr.io/{owner}/{repo}:version
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          # See:
          # https://github.com/opencontainers/image-spec/blob/79b036d80240ae530a8de15e1d21c7ab9292c693/annotations.md
          # Note that org.opencontainers.image.source will allow Github to link this image to this
          # repo
          build-args: |
            created=\"${{ steps.date.output.date }}\"
            url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
            version="${{ github.event.release.tag_name }}"
            revision="$GITHUB_SHA"
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
